#!/bin/sh

IMAGE='localhost/code-challenge/yarn'

read -r -d '' CONTAINERFILE <<'EOF'
FROM docker.io/node:20-alpine3.18

VOLUME ["/repo"]
WORKDIR /repo

RUN apk add --no-cache dumb-init git

ENTRYPOINT ["dumb-init", "--", "yarn"]
EOF

DIR_ROOT=$(realpath "$PWD")

build () {
    echo "$CONTAINERFILE" | podman build -t "$IMAGE" --file - --no-cache
    local result=$?

    return $result
}

run () {
    podman \
        run \
            --userns keep-id \
            -it \
            --rm \
            -v "$DIR_ROOT":/repo \
        "$IMAGE" $@
}

is_container_built () {
    podman image exists "$IMAGE"
}

if ! is_container_built; then
  build || exit
fi

run $@
